### ISSUE TITLE
shdict_get flag comparison

### ISSUE THREAD

**Issue by Miniwoffer** [openresty/lua-nginx-module#1921]
## Proposal
Add optional flags argument to ```shmdict_get(_stale)?```  that only returns value if flags *do not* match.
And a third return value to indicate if it is a flag match.

## Exsample usage
``` lua
local cfg = lru:get(key) or empty_table
local serialized, err, flag_match = shm:get(key, (cfg or empty_table).version)
if flag_match then
        return cfg
end

if not serialized then
        return nil, err
end

cfg, err = cjson.decode(serialized)
if not cfg then
        return nil, err
end

lru:set(key, cfg)

return cfg
```
## Why?
Allocating and collecting the memory nedded to return a value can be
very expensive when value is not needed.

## Bencmarking:
[Link to benchmark repo](https://github.com/Miniwoffer/shmdict_benchmark)
Read only benchmarking, with random access order.
Tested with 5 000 000 shm lookups on a single worker.
```
Value 2048 bytes string
  Results: ~75.8% faster

Value 1024 bytes string
  Results: ~46.8% faster

Value 256 bytes string
  Results: ~24.7% faster

Value 16 byte string
  Results: ~19.8% faster

Value number
  Results: ~5.4% faster
```

**Comment by doujiang24** [comment]
Hi @Miniwoffer
I think we also need to think about if the new API is slower than before when there is no flag used, could you please provide some bench results?

**Comment by Miniwoffer** [comment]
Sure, i had som trouble getting consistent results betwene runs, but managed to get some more or less reliable data.
Benchmarked with numbers, no random order and ran it for 1 800 000 000 gets.

```
728602.81 +- 0.30401007181484 % -- with flags
727996.34 +- 0.24869427024663 % -- without flags
100.0833067375 %
```

**Comment by Miniwoffer** [comment]
Any progress?

**Comment by zhuizhuhaomeng** [comment]
@miniwoffer, please rebase to the master and change the lua-resty-core in .travis.yml to your branch.

**Comment by zhuizhuhaomeng** [comment]
we need to update the api in doc/HttpLuaModule.wiki.

**Comment by Miniwoffer** [comment]
@zhuizhuhaomeng Done, travis is green on lua-nginx-module but not lua-resty-core. But master is also red, so i am unsure if its me.

**Comment by Miniwoffer** [comment]
Okay so there are some tests in lua-resty-core that uses get and get_stale with two arguments. Dont know why those tests specify a secound argument, so would need some guidance on how to alter those tests.

Also want me to write tests for lua-rest-core even though the tests in lua-nginx-module should cover everything?

**Comment by Miniwoffer** [comment]
Fixed so Test 24 and 25 in t/shdict.t pass, just changed so key == nil is check first.

**Comment by zhuizhuhaomeng** [comment]
lua-resty-core still failed.
https://app.travis-ci.com/github/openresty/lua-resty-core/builds/239052924

**Comment by Miniwoffer** [comment]
@zhuizhuhaomeng Yeah sorry about that, thought stream was generated from http so didn't implement anything in stream. I ported tho code and the tests over to the stream module.

**Comment by agentzh** [comment]
I think it's better to introduce a new Lua method instead of piggybacking the existing `get()` method.

**Comment by bjne** [comment]
Do you have a suggestion, @agentzh? get_conditional(key, flags) ? perhaps (key, flags, comparator) with comparator defaulting to "~="

**Comment by agentzh** [comment]
@bjne I've found the semantics a bit confusing. I don't see equivalents in redis or memcached's API. What exactly is your use case here? You're using flags as some kind of version number here? We'd better set the semantics straight first?

**Comment by bjne** [comment]
We are doing multilevel caching, db -> shm -> lru, but due to lack of (or complexity/performance) or IPC between threads, we are using the lru and shm uint32 flags to store a version of the object (actually just time of shm-insert in ms % 2^32) with a ttl of half that, but it could be any versioning ofcorse.

To keep updates to config available fast, we now get flags and value from shm, and then compare with lru flags and if they are same no need to deserialize.

This is where this idea was born, what performance can be gained from not getting the value at all from shm if we do not need it. And as shown above, quite significant numbers.

The closest thing found in redis I guess is for the SET actual, CAS (compare-and-swap), dont know if COG (compare-or-get) exists in that context, but that is what we want. At the moment I only see the use for the 'NE' comparator, so I am fine with implementing without a comparator input or eventually with 'NE' as the default.

**Comment by bjne** [comment]
@agentzh ping

**Comment by agentzh** [comment]
BTW, we also provide lua-resty-jsonb library which does not need any serialization or de-serialization overhead when storing JSON data in shm. But it's not open source. You can contact info@openresty.com if you're interested.
