### ISSUE TITLE
PCRE2 Support

### ISSUE THREAD

**Issue by kn007** [openresty/lua-nginx-module#1984]
Compile failed.

Nginx 1.21.5:
now nginx is built with the PCRE2 library by default.

```
/tmp/nginx.lJpu0R.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_log_by_chunk: error: undefined reference to 'pcre_malloc'
/tmp/nginx.lJpu0R.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_log_by_chunk: error: undefined reference to 'pcre_free'
/tmp/nginx.lJpu0R.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_log_by_chunk: error: undefined reference to 'pcre_malloc'
/tmp/nginx.lJpu0R.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_log_by_chunk: error: undefined reference to 'pcre_free'
/tmp/nginx.lJpu0R.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_body_filter_by_chunk: error: undefined reference to 'pcre_malloc'
/tmp/nginx.lJpu0R.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_body_filter_by_chunk: error: undefined reference to 'pcre_free'
/tmp/nginx.lJpu0R.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_body_filter_by_chunk: error: undefined reference to 'pcre_free'
/tmp/nginx.lJpu0R.ltrans12.ltrans.o:<artificial>:function ngx_http_lua_pcre_malloc_done: error: undefined reference to 'pcre_malloc'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_destroy_regex: error: undefined reference to 'pcre_free_study'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_destroy_regex: error: undefined reference to 'pcre_free_study'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_exec_regex: error: undefined reference to 'pcre_dfa_exec'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_exec_regex: error: undefined reference to 'pcre_exec'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_set_jit_stack_size: error: undefined reference to 'pcre_jit_stack_free'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_set_jit_stack_size: error: undefined reference to 'pcre_jit_stack_alloc'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_set_jit_stack_size: error: undefined reference to 'pcre_jit_stack_alloc'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_set_jit_stack_size: error: undefined reference to 'pcre_jit_stack_free'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_compile'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_fullinfo'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_study'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_assign_jit_stack'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_fullinfo'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_study'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_free_study'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_free_study'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_fullinfo'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_study'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_study'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_fullinfo'
/tmp/nginx.lJpu0R.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_pcre_version: error: undefined reference to 'pcre_version'
```

==============

it's time
https://github.com/openresty/lua-nginx-module/issues/577#issuecomment-146131885

![20211230231358](https://user-images.githubusercontent.com/6196903/147764090-4fb6fbed-b0cc-41c0-b9c2-c1c816b22470.png)

![20211230231523](https://user-images.githubusercontent.com/6196903/147764190-b7e8aebc-4e61-4901-a734-3923f27bb992.png)

**Comment by yangzhaofeng** [comment]
Here is a workaround:

add `-lpcre` in `--with-ld-opt` when running `configure`, for example
```
./configure --with-compat --with-ld-opt='-lpcre' --add-dynamic-module=../ngx_devel_kit-${DEVEL_KIT_VERSION} --add-dynamic-module=../lua-nginx-module-${LUA_MODULE_VERSION}
```

**Comment by kn007** [comment]
@yangzhaofeng Yes, I I have do it 5 days ago. But this is not the solution I want.

**Comment by steamboatid** [comment]
i can confirm this error w/ nginx 1.21.6

**Comment by pgnd** [comment]
for anyone interested,

an alternative that covers my scripting needs is migrating current lua+nginx functionality over to njs.

it's closely aligned to upstream nginx, clearly, building nicely with latest nginx, pcre2, etc.

and for my needs looks like i'll be able to cover all existing lua-script functionality.

not for everyone, but trimming down to one scripting environment is attractive ...

**Comment by eilandert** [comment]
any idea if there are plans to fix this?

**Comment by cleverpig** [comment]
any idea if there are plans to fix this? keep watching.

**Comment by zhuizhuhaomeng** [comment]
will support pcre2 when upgrading to version 1.21.6

**Comment by kn007** [comment]
> will support pcre2 when upgrading to version 1.21.6

@zhuizhuhaomeng 

Compile failed with nginx 1.21.6

```
/tmp/nginx.3QZ5G3.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_log_by_chunk: error: undefined reference to 'pcre_malloc'
/tmp/nginx.3QZ5G3.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_log_by_chunk: error: undefined reference to 'pcre_free'
/tmp/nginx.3QZ5G3.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_log_by_chunk: error: undefined reference to 'pcre_malloc'
/tmp/nginx.3QZ5G3.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_log_by_chunk: error: undefined reference to 'pcre_free'
/tmp/nginx.3QZ5G3.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_body_filter_by_chunk: error: undefined reference to 'pcre_malloc'
/tmp/nginx.3QZ5G3.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_body_filter_by_chunk: error: undefined reference to 'pcre_free'
/tmp/nginx.3QZ5G3.ltrans10.ltrans.o:<artificial>:function ngx_http_lua_body_filter_by_chunk: error: undefined reference to 'pcre_free'
/tmp/nginx.3QZ5G3.ltrans12.ltrans.o:<artificial>:function ngx_http_lua_pcre_malloc_done: error: undefined reference to 'pcre_malloc'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_destroy_regex: error: undefined reference to 'pcre_free_study'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_destroy_regex: error: undefined reference to 'pcre_free_study'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_exec_regex: error: undefined reference to 'pcre_dfa_exec'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_exec_regex: error: undefined reference to 'pcre_exec'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_set_jit_stack_size: error: undefined reference to 'pcre_jit_stack_free'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_set_jit_stack_size: error: undefined reference to 'pcre_jit_stack_alloc'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_set_jit_stack_size: error: undefined reference to 'pcre_jit_stack_alloc'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_set_jit_stack_size: error: undefined reference to 'pcre_jit_stack_free'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_compile'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_fullinfo'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_study'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_assign_jit_stack'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_fullinfo'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_study'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_free_study'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_free_study'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_fullinfo'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_study'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_study'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_compile_regex: error: undefined reference to 'pcre_fullinfo'
/tmp/nginx.3QZ5G3.ltrans13.ltrans.o:<artificial>:function ngx_http_lua_ffi_pcre_version: error: undefined reference to 'pcre_version'
```

**Comment by kn007** [comment]
How is the progress going?

**Comment by xiaocang** [comment]
Hi @kn007, we will probably support pcre2 when openresty is upgraded to 1.21.6.x (based on nginx 1.21.6). It looks like some of these modules need to have some patches applied for them to work properly

**Comment by msva** [comment]
@xiaocang can we have any estimated timeframe for when it will happen, please?

**Comment by xiaocang** [comment]
@msva Perhaps in the next quarter, and relevant PR would be welcome.

**Comment by bagasik** [comment]
Hello.
nginx-1.22 lua-resty-core-0.1.23 not working.

My system FreeBSD 12.3-RELEASE-p5 amd64.
Installed ports:
nginx-1.22.0,2
lua-resty-core-0.1.23
pcre-8.45_1
pcre2-10.40

Error:
nginx -t
nginx: [emerg] dlopen() "/usr/local/libexec/nginx/ngx_http_lua_module.so" failed (/usr/local/libexec/nginx/ngx_http_lua_module.so: Undefined symbol "pcre_free") in /usr/local/etc/nginx/nginx.conf:2
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed

**Comment by jirutka** [comment]
This happens when you build nginx with pcre2, but the Lua module with pcre. These cannot be mixed. Sadly, you have to build nginx withou pcre2 to use the Lua module.

**Comment by bagasik** [comment]
How can I make nginx without pcre2?

**Comment by bagasik** [comment]
nginx is built --with-pcre.

nginx -V
nginx version: nginx/1.20.2
built with OpenSSL 1.1.1l-freebsd  24 Aug 2021
TLS SNI support enabled
configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --user=www --group=www --with-compat --modules-path=/usr/local/libexec/nginx --with-file-aio --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx/access.log --with-http_v2_module --with-http_addition_module --with-http_auth_request_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_realip_module --with-pcre --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-cc-opt='-DNGX_HAVE_INET6=0 -I /usr/local/include' --without-mail_imap_module --without-mail_pop3_module --without-mail_smtp_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-stream=dynamic --add-dynamic-module=/mnt/111/nginx/work/ngx_devel_kit-0.3.1 --add-dynamic-module=/mnt/111/nginx/work/lua-nginx-module-0.10.20

**Comment by jirutka** [comment]
> How can I make nginx without pcre2?

`--without-pcre2`

**Comment by dvershinin** [comment]
> This happens when you build nginx with pcre2, but the Lua module with pcre. These cannot be mixed. Sadly, you have to build nginx withou pcre2 to use the Lua module.

You can mix them in this way, as long as `-lpcre` is added (as mentioned in one of the previous comments).

**Comment by bagasik** [comment]
Hello.
When will the situation in (nginx+lua) with pcre2 be fixed?

Didn't understand about -lpcre.
Please explain in more detail.
What is -lpcre ?

**Comment by dvershinin** [comment]
@bagasik [this comment](https://github.com/openresty/lua-nginx-module/issues/1984#issuecomment-1003709530) explains it clearly. What problems are you having?

**Comment by bagasik** [comment]
What is this -lpcre parameter.
Do I need to rebuild the pcre2 port with this parameter?

**Comment by splitice** [comment]
@earas lua-nginx-module doesnt support http3 anyway. #741

**Comment by xiaocang** [comment]
> I am having the same problem. nginx 1.21.5 and 1.21.6 comes with PCRE2. And Lua is incompatible with that.
@earas, You're right, to support PCRE2 some more PRs are needed

**Comment by borats** [comment]
> You're right, to support PCRE2 some more PRs are needed

@xiaocang perhaps have a milestone where people fluent in Go/Lua, *NIX, Build infra can contribute to the effort of aligning upstream version more easily with kubernetes/ingress-nginx. I believe, the critical mass of `kubernetes/ingress-nginx` is now at a point where we need to move this needle more rapidly than authors envisioned. Personally, sponsorship of project/s _could_ potentially help too.

**Comment by jirutka** [comment]
I’d suggest moving from nginx Lua to njs (NGINX JavaScript). It’s being developed directly by NGINX, so better supported. I’ve created tooling for developing and testing njs extensions in TypeScript (or plain JavaScript). You can start with [njs-typescript-starter](https://github.com/jirutka/njs-typescript-starter) (note: it’s a bit outdated now, njs already supports async/await, but it should work; I’ll update it later).

**Comment by kn007** [comment]
@jirutka The njs does not support I/O operations, execute external programs...

**Comment by splitice** [comment]
njs has very different design parameters to openresty (and Lua support in general).

I'll be the last person to state that the openresty ecosystem community (developer contributions, merging and triage) is well run, well resourced and working optimally but irrespective of that it's a good platform. The base is good it's the community aspects that have failed.

I could supply example pr's from the past. There are many examples of complete features with real applications that never merged (incr extentions and cas come to mind).

**Comment by leeiitb** [comment]
Waiting for PCRE2 support 🤔
Thanks

**Comment by kn007** [comment]
I think they will support it in Apr 2023😂

**Comment by msva** [comment]
> in Apr 2023

Why did you chose that ETA?
Are there any rumors/insight?


// btw, one more +1 to increase priority of adding PCRE2 support

**Comment by AsocPro** [comment]
I too am waiting on this from the kubernetes/ingress-nginx side of things.

Is there anywhere that defines the required scope of work here or someone who can break down in more detail what the change to PCRE2 entails? I am not an expert on the openresty module side of things but maybe if there was someone that could give a little guidance there are things that could be worked on by people here (I include myself) that does fit with our experience.

**Comment by muuvmuuv** [comment]
Might rename this issue to "PCRE2 Support" to be more specific?

**Comment by kn007** [comment]
still no progress.

OpenResty based on 1.21.4

Nginx mainline version: 1.23.4

**Comment by mapicccy** [comment]
Wait for PCRE2 supporting.
The older PCRE version has been at **end of life**.
Thanks

**Comment by eilandert** [comment]
> I think they will support it in Apr 2023😂

Or maybe Apr 2024

**Comment by kn007** [comment]
> > I think they will support it in Apr 2023😂
> 
> Or maybe Apr 2024

The latest version of Nginx is 1.25.1. 
The version of openresty has been 1.21.4(Actually 1.21.4.2 RC1) for a long time. Even if it has a small version update. I don't think there will be any major updates in a short time unless there are new helpers.

**Comment by kn007** [comment]
Maybe fixed by https://github.com/openresty/lua-nginx-module/commit/cb83e33e26579788be0fe0282fa5976de6dfa6e3

**Comment by qu1j0t3** [comment]
Confirming this is still a problem with `nginx:1.24-alpine` and `nginx-mod-http-lua (1.22.1-r1)`:

```
app-1     | 2025/05/10 02:27:24 [emerg] 1#1: dlopen() "/etc/nginx/modules/ngx_http_lua_module.so" failed (Error relocating /etc/nginx/modules/ngx_http_lua_module.so: pcre_dfa_exec: symbol not found) in /etc/nginx/nginx.conf:7
app-1     | nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_lua_module.so" failed (Error relocating /etc/nginx/modules/ngx_http_lua_module.so: pcre_dfa_exec: symbol not found) in /etc/nginx/nginx.conf:7
```

**Comment by msva** [comment]
This issue was about building with pcre2. And it seems like you're talking about about binary incompatibility between nginx built by random anon and lua module built by another random anon.

**Comment by qu1j0t3** [comment]
No, if you read more carefully, these are Alpine packages. Can this be made to work outside Alpine from source builds? Maybe. But the nginx and nginx lua module packages don't interoperate. Perhaps that is reportable to Alpine. 

In any case, the aggravation wasn't worth it; I used the JS module instead, which had no integration problems.

**Comment by msva** [comment]
Still, your issue is barely related to this one.

Lua module has pcre2 compatibility implemented for a pretty long time already.


So you should talk with alpine maintainer(s) of this packages about your problem, so they will fix the build scripts.


(Or probably you can ignore all of this, as you had already confessed to be an js-imposter 🤷 )

**Comment by jirutka** [comment]
> So you should talk with alpine maintainer(s) of this packages about your problem, so they will fix the build scripts.

I’m here… I found out that lua-nginx-module finally supports PCRE2 just a few days ago. There’s a problem with some tests failing on riscv64 after switching to PCRE2 though.

Anyway, mixing completely different builds and versions of nginx and modules is unsupported and unrelated to PCRE2.
