### ISSUE TITLE
content_by_lua_block not parsing complex tables

### ISSUE THREAD

**Issue by alubbe** [openresty/lua-nginx-module#611]
Thanks for releasing the new *_by_lua_block!
I was able to convert almost all occurences of my inline lua to the new syntax - except one. Here is a simple way to reconstruct the error I am getting:
```nginx
        location /test {
            content_by_lua_block {
                local asd = {
                    ["b"] = {
                        asd = 2
                    }
                }
                ngx.print(toJSON({
                    ["b"] = {
                        asd = 2
                    }
                }))
            }
        }
```
crashes with
```
nginx: [emerg] Lua code block missing the "}" character
```
I'm assuming there is something going on here with the number of nested tables that add a lot of `}` characters and the way the parsing is implemented.

**Comment by doujiang24** [comment]
@alubbe which version of OpenResty you are using?
It works fine with ngx_openresty-1.9.3.2

```lua
    location = /t {
        content_by_lua_block {
            local cjson = require "cjson"
            local asd = {
                ["b"] = {
                    asd = 2
                }
            }
            ngx.print(cjson.encode({
                ["b"] = {
                    asd = 2
                }
            }))
        }
    }
```

```shell
curl -i http://127.0.0.1:1984/t
{"b":{"asd":2}}
```

**Comment by alubbe** [comment]
Hi @doujiang24, you are right, it does work in isolation. The issue turns out to have to do with the total file-wide amount of lua code. Here's a full file that will cause the error:
```nginx
worker_processes  6;
events {
    worker_connections 1024;
}
http {
    server {
        listen 80;
        location /test {
            content_by_lua_block {
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
            }
        }
        location /test2 {
            content_by_lua_block {
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
            }
        }
        location /test3 {
            content_by_lua_block {
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
                "this is just some random filler to cause an error"
            }
        }
    }
}
```

**Comment by agentzh** [comment]
@alubbe This is what I need. Thanks for the bug report and test case! Fixed in master as commit 94f68befa

**Comment by agentzh** [comment]
@alubbe Please let me know if that patch works for you.

**Comment by alubbe** [comment]
I've patched ngx_openresty-1.9.3.2/build/ngx_lua-0.9.19/src/ngx_http_lua_directive.c and rebuilt, but I still get 
```
nginx: [emerg] Lua code block missing the "}" character in /.../conf/nginx.conf:72
```
I ran
```
./configure --with-http_spdy_module --with-debug --with-pcre=$HOME/Downloads/pcre-8.37 --with-pcre-jit -j9
make -j9
sudo make install
```

**Comment by agentzh** [comment]
@alubbe You are patching the wrong file. The `build/` directory is always wiped out during `./configure`. You should patch the file under `bundle/` instead.

**Comment by agentzh** [comment]
@alubbe BTW, it's easier to create a symlink under `bundle/` to point to your local clone of the git repos of lua-nginx-module.

**Comment by alubbe** [comment]
I figured it was something like that.
Patch works - issue solved. Thanks!
